name: "Bug Report (English)"
description: Create a bug report to help us improve our content.
title: "[BUG] - Missing test case"
labels: []
body:
  - type: input
    id: username
    attributes:
      label: "LeetCode Username"
      description: Click your avatar in the top right on the problem page after logging in to find your username.
    validations:
      required: true
  - type: input
    id: problem-details
    attributes:
      label: "Problem Number, Title, and Link"
      placeholder: 1. Count Pairs Whose Sum is Less than Target https://leetcode.com/problems/count-pairs-whose-sum-is-less-than-target/description/
    validations:
      required: true
  - type: dropdown
    id: bug-category
    attributes:
      label: "Bug Category"
      multiple: true
      options:
        - Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: In the description it is given that return the number of pairs (i, j) where 0 <= i < j < n, meaning the order of the pair matters. However, if the list is sorted and pairs are found, it is still accepted.
    validations:
      required: true
  - type: dropdown
    id: language-used
    attributes:
      label: "Language Used for Code"
      options:
        - Java
    validations:
      required: false
  - type: textarea
    id: code
    attributes:
      label: Code used for Submit/Run operation
      description: Please copy and paste the complete code you used for submit/run operation. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: The solution should not be accepted if the originally given order of pairs is not followed.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to explain the issue.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other additional context about the bug.
    validations:
      required: false
