name: "Bug Report (English)"
description: Create a bug report to help us improve our content.
title: "[BUG] - <title>"
labels: []
body:
  - type: input
    id: username
    attributes:
      label: "LeetCode Username"
      "hiro_case"
      description: Click your avatar in the top right on the problem page after logging in to find your username.
    validations:
      required: true
  - type: input
    id: problem-details
    attributes:
      label: "Problem Number, Title, and Link"
      placeholder: 8. String to Integer (atoi) https://leetcode.com/problems/string-to-integer-atoi/
    validations:
      required: true
  - type: dropdown
    id: bug-category
    attributes:
      label: "Bug Category"
      multiple: true
      placeholder: Editorial
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      placeholder: Wrong type in functions. Two of the functions in the state machine object say "-> None" but they actually return int

      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: dropdown
    id: language-used
    attributes:
      label: "Language Used for Code"
      language: Python/Python3
      options:
        - Python/Python3
        
    validations:
      required: false
  - type: textarea
    id: code
    attributes:
      label: Code used for Submit/Run operation
      here is the fix:
      def get_integer(self) -> int:
        """Return the final result formed with it's sign."""
        return self.__sign * self.__result

      def get_state(self) -> int:
        """Get current state."""
        return self.__current_state

      
      description: Please copy and paste the complete code you used for submit/run operation. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    - The functions currently show the following indicating they return nothing
    def get_integer(self) -> None:
        """Return the final result formed with it's sign."""
        return self.__sign * self.__result

    def get_state(self) -> None:
        """Get current state."""
        return self.__current_state
    - However, ther functions return integers 

      description: A clear and concise description of what was expected to happen in contrast with what happened.
       
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to explain the issue.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other additional context about the bug.
    validations:
      required: false
